on:
  push:
    branches:
      - main
      - release/v0

jobs:
  clippy_check_cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-hub/docker/cli@f5fdbfc3f9d2a9265ead8962c1314108a7b7ec5d
        env:
          SKIP_LOGIN: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-09-13
          override: true
          components: rustfmt, clippy
      - name: Compile project
        run: cargo build --all-features -p ev-cage -Z registry-auth
        env:
          CARGO_REGISTRIES_EVERVAULT_RUST_LIBRARIES_INDEX: ${{ secrets.RUST_CRYPTO_REGISTRY }}
          CARGO_REGISTRIES_EVERVAULT_RUST_LIBRARIES_TOKEN: ${{ secrets.CARGO_REGISTRIES_EVERVAULT_RUST_LIBRARIES_TOKEN }}
      - name: Test project
        run: cargo test -p ev-cage
        env:
          CARGO_REGISTRIES_EVERVAULT_RUST_LIBRARIES_INDEX: ${{ secrets.RUST_CRYPTO_REGISTRY }}
      - name: Format project
        run: cargo fmt --check
        env:
          CARGO_REGISTRIES_EVERVAULT_RUST_LIBRARIES_INDEX: ${{ secrets.RUST_CRYPTO_REGISTRY }}
      - name: Lint project
        run: cargo clippy
        env:
          CARGO_REGISTRIES_EVERVAULT_RUST_LIBRARIES_INDEX: ${{ secrets.RUST_CRYPTO_REGISTRY }}

  get-version:
    needs: [clippy_check_cli]
    runs-on: ubuntu-latest
    outputs:
      major-version: ${{ steps.get-major.outputs.major-version }}
      full-version: ${{ steps.get-full-version.outputs.full-version }}
    steps:
      - uses: actions/checkout@v4
      - id: get-major
        env:
          MAJOR: ${{ steps.get-major.outputs.major-version }}
          CARGO_REGISTRIES_EVERVAULT_RUST_LIBRARIES_INDEX: ${{ secrets.RUST_CRYPTO_REGISTRY }}
          CARGO_REGISTRIES_EVERVAULT_RUST_LIBRARIES_TOKEN: ${{ secrets.CARGO_REGISTRIES_EVERVAULT_RUST_LIBRARIES_TOKEN }}
        run: |
          MAJOR=$(cargo metadata --no-deps | jq -r '.packages[] | select(.name == "ev-cage") | .version[0:1]')
          echo "major-version=$MAJOR" >> "$GITHUB_OUTPUT"

      - id: get-full-version
        env:
          MAJOR: ${{ steps.get-major.outputs.major-version }}
        run: |
          echo "using sha tag ${GITHUB_SHA::6}"
          echo "full-version=$MAJOR.0.0-${GITHUB_SHA::6}" >> "$GITHUB_OUTPUT"
          
  build-and-deploy:
    needs: [get-version]
    uses: ./.github/workflows/build-and-publish.yml
    with:
      stage: 'staging'
      major-version: "${{ needs.get-version.outputs.major-version }}" 
      full-version: "${{ needs.get-version.outputs.full-version }}"
      ev-domain: 'evervault.io'
      base-branch: ${{ github.ref }}
    secrets:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
        aws-cloudfront-distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_STAGING }}
        evervault-rust-lib-index: ${{ secrets.RUST_CRYPTO_REGISTRY }}
        evervault-rust-lib-token: ${{ secrets.CARGO_REGISTRIES_EVERVAULT_RUST_LIBRARIES_TOKEN }}
